config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :records

  root 'welcome#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
   def index
      @records = Record.all
    end

    def create
      @record = Record.new(record_params)

      if @record.save
        render json: @record
      else
        render json: @record.errors, status: :unprocessable_entity
      end
    end

    def update
      @record = Record.find(params[:id])
      if @record.update(record_params)
        render json: @record
      else
        render json: @record.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @record = Record.find(params[:id])
      @record.destroy
      head :no_content
    end




    private

      def record_params
        params.require(:record).permit(:title, :amount, :date)
      end
      
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactAccount</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <%= link_to 'Home', root_path  %> | <%= link_to 'Page de payments', records_path  %>
</nav>

<%= yield %>

</body>
</html>

app/views/records/index.html.erb
<%# render react component records.js %>

<%= react_component 'Records', { data: @records } %>

app/views/welcome/index.html.erb
Home page